quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  hibernate-orm:
    database:
      generation: update

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    locations: db/migration

  hibernate-validator:
    fail-fast: true

  minio:
    url: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    public:
      secure: false

  # JWT Configuration
smallrye:
  jwt:
    sign:
      key:
        location: rsaPrivateKey.pem

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: ${JWT_ISSUER:https://occ.agora.org}

app:
  minio:
    url: ${MINIO_URL}
    bucket: ${MINIO_BUCKET}
