package org.agora.occ.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.agora.occ.enums.DangerLevel;
import org.agora.occ.enums.WarningLevel;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Entity representing a safety warning alert generated by a JPL system.
 */
@Entity
@Table(name = "warning")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WarningEntity {

    @Id
    @Column(name = "alert_id")
    private UUID alertId;

    @ManyToOne
    @JoinColumn(name = "jpl_id", nullable = false)
    private JplEntity jpl;

    @Column(name = "camera_id", length = 100)
    private String cameraId;

    @Column(name = "jpl_code", length = 100)
    private String jplCode;

    @Column(name = "jpl_name")
    private String jplName;

    @Column(name = "train_id", nullable = false)
    private UUID trainId;

    @Column(name = "train_name")
    private String trainName;

    @Column(name = "train_code", length = 100)
    private String trainCode;

    @Enumerated(EnumType.STRING)
    @Column(name = "crowd_level", length = 50)
    private DangerLevel crowdLevel;

    @Enumerated(EnumType.STRING)
    @Column(name = "warning_level", length = 50)
    private WarningLevel warningLevel;

    @Column(name = "distance_km")
    private Double distanceKm;

    @Column(name = "speed_kmh")
    private Double speedKmh;

    @Column(name = "object_detected")
    private Integer objectDetected;

    @Column(name = "alert_timestamp", nullable = false)
    private Instant alertTimestamp;

    @Column(name = "action_required", columnDefinition = "TEXT")
    private String actionRequired;

    @Column(name = "color_indicator", length = 50)
    private String colorIndicator;

    @Column(name = "is_health")
    private Boolean isHealth;

    @Column(name = "is_siren_on")
    private Boolean isSirenOn;

    @Column(name = "is_gate_open")
    private Boolean isGateOpen;

    @Column(name = "is_any_obstacle")
    private Boolean isAnyObstacle;

    @Column(name = "is_installed")
    private Boolean isInstalled;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "camera_stream", columnDefinition = "text[]")
    private List<String> cameraStream;
}
